//-----------------------------------------------------------------------
// <copyright file="Ibase_userRepository.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BaseUser.cs
// * history : Created by T4 11/21/2018 23:47:56 
// </copyright>
//-----------------------------------------------------------------------
using System; 

namespace BuDing.Repository.ContractRepository
{
	using BuDing.Sunrise.Models;
	using BuDing.Infrustructure.Contract.DataLogic;

    /// <summary>
    /// BaseUserRepository Entity Repository
    /// </summary> 
    public partial interface IBaseUserRepository:IRepository<BaseUser>
    {
 
    }
}
