//-----------------------------------------------------------------------
// <copyright file="Isys_moduleRepository.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysModule.cs
// * history : Created by T4 11/26/2018 22:43:46 
// </copyright>
//-----------------------------------------------------------------------
using System; 

namespace BuDing.Application.Interfaces.IRepositories
{
    using BuDing.Domain.Entities;
    using BuDing.Infrastructure.DataLogic;

    /// <summary>
    /// SysModuleRepository Entity Repository
    /// </summary> 
    public partial interface ISysModuleRepository:IRepository<SysModuleEntity>
    {
 
    }
}
