//-----------------------------------------------------------------------
// <copyright file="sys_module.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysModule.cs
// * history : Created by T4 11/27/2018 23:35:36 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuDing.Domain.Entities
{
    /// <summary>
    /// SysModule Entity Model
    /// </summary>
    [Serializable]
    [Table("sys_module")]
    public partial class SysModuleEntity: BaseEntity
    {
        public SysModuleEntity() { }
          
        /// <summary>
        /// 上级ID
        /// </summary>
        public int? ParentID { get; set; }
        
        /// <summary>
        /// 编号
        /// </summary>
        [StringLength(100)]
        public string Code { get; set; }
        
        /// <summary>
        /// 菜单名称
        /// </summary>
        [StringLength(20)]
        public string Name { get; set; }
        
        /// <summary>
        /// 显示名称
        /// </summary>
        [StringLength(20)]
        public string DisplayName { get; set; }
        
        /// <summary>
        /// 全称
        /// </summary>
        [StringLength(50)]
        public string FullName { get; set; }
        
        /// <summary>
        /// 菜单分类SystemApplication
        /// </summary>
        [StringLength(50)]
        public string CategoryCode { get; set; }
        
        /// <summary>
        /// 菜单地址
        /// </summary>
        [StringLength(500)]
        public string Url { get; set; }
        
        /// <summary>
        /// 排序码
        /// </summary>
        public int? SortCode { get; set; }
        
        /// <summary>
        /// 是否是菜单（0：否，1:是）
        /// </summary>
        public bool? IsMenu { get; set; }
        
        /// <summary>
        /// 图标
        /// </summary>
        [StringLength(100)]
        public string Icon { get; set; }
        
        /// <summary>
        /// 是否公开（0：否，1:是）
        /// </summary>
        public bool? IsPublic { get; set; }
        
        /// <summary>
        /// 是否有效（0：否，1:是）
        /// </summary>
        public bool? IsEnabled { get; set; }
        
        /// <summary>
        /// 删除标识（0：否，1:是）
        /// </summary>
        public bool? DeletionStateCode { get; set; }
        
        /// <summary>
        /// 是否显示（0：否，1:是）
        /// </summary>
        public bool? IsVisable { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(300)]
        public string Remark { get; set; }
        
    }
}
