//-----------------------------------------------------------------------
// <copyright file="sys_role.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysRole.cs
// * history : Created by T4 11/27/2018 23:35:36 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuDing.Domain.Entities
{
    /// <summary>
    /// SysRole Entity Model
    /// </summary>
    [Serializable]
    [Table("sys_role")]
    public partial class SysRole: BaseEntity
    {
        public SysRole() { } 
        
        /// <summary>
        /// 模块ID
        /// </summary>
        public int? ModuleID { get; set; }
        
        /// <summary>
        /// 角色编号
        /// </summary>
        [StringLength(20)]
        public string Code { get; set; }
        
        /// <summary>
        /// 角色名称
        /// </summary>
        [StringLength(50)]
        public string RealName { get; set; }
        
        /// <summary>
        /// 角色分类
        /// </summary>
        [StringLength(50)]
        public string CateGoryCode { get; set; }
        
        /// <summary>
        /// 允许编辑（0：否，1:是）
        /// </summary>
        public bool? AllowEdit { get; set; }
        
        /// <summary>
        /// 允许删除（0：否，1:是）
        /// </summary>
        public bool? AllowDelete { get; set; }
        
        /// <summary>
        /// 是否显示（0：否，1:是）
        /// </summary>
        public bool? IsVisible { get; set; }
        
        /// <summary>
        /// 排序码
        /// </summary>
        public int? SortCode { get; set; }
        
        /// <summary>
        /// 删除标识（0：否，1:是）
        /// </summary>
        public bool? DeletionStateCode { get; set; }
        
        /// <summary>
        /// 是否有效（0：否，1:是）
        /// </summary>
        public bool? IsEnabled { get; set; }
        
        /// <summary>
        /// 描述
        /// </summary>
        [StringLength(100)]
        public string Description { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(300)]
        public string Remark { get; set; }
       
    }
}
