//-----------------------------------------------------------------------
// <copyright file="sys_user_role.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysUserRole.cs
// * history : Created by T4 11/27/2018 23:35:36 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuDing.Domain.Entities
{
    /// <summary>
    /// SysUserRole Entity Model
    /// </summary>
    [Serializable]
    [Table("sys_user_role")]
    public partial class SysUserRole: BaseEntity
    {
        public SysUserRole() { } 
        
        /// <summary>
        /// 角色ID
        /// </summary>
        public int? RoleID { get; set; }
        
        /// <summary>
        /// 删除标识（0：否，1:是）
        /// </summary>
        public bool? DeletionStateCode { get; set; }
        
        /// <summary>
        /// 是否有效（0：否，1:是）
        /// </summary>
        public bool? IsEnabled { get; set; }
        
        /// <summary>
        /// 描述
        /// </summary>
        [StringLength(100)]
        public string Description { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(300)]
        public string Remark { get; set; }
        
    }
}
