//-----------------------------------------------------------------------
// <copyright file="sys_user.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysUser.cs
// * history : Created by T4 11/27/2018 23:35:36 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuDing.Domain.Entities
{
    /// <summary>
    /// SysUser Entity Model
    /// </summary>
    [Serializable]
    [Table("sys_user")]
    public partial class SysUser
    {
        public SysUser() { }
        
        /// <summary>
        /// ID
        /// </summary>
        [Key]  
        [StringLength(20)]
        public string ID { get; set; }
        
        /// <summary>
        /// 用户名
        /// </summary>
        [StringLength(50)]
        public string Name { get; set; }
        
        /// <summary>
        /// 密码
        /// </summary>
        [StringLength(255)]
        public string Passwrod { get; set; }
        
        /// <summary>
        /// 昵称
        /// </summary>
        [StringLength(255)]
        public string DispName { get; set; }
        
        /// <summary>
        /// 性别
        /// </summary>
        public int? Sex { get; set; }
        
        /// <summary>
        /// 邮箱
        /// </summary>
        [StringLength(50)]
        public string Mail { get; set; }
        
        /// <summary>
        /// 手机号码
        /// </summary>
        [StringLength(20)]
        public string Mobile { get; set; }
        
        /// <summary>
        /// 头像
        /// </summary>
        [StringLength(50)]
        public string Avatar { get; set; }
        
        /// <summary>
        /// 身份证号
        /// </summary>
        [StringLength(30)]
        public string IdentityCode { get; set; }
        
        /// <summary>
        /// 地址
        /// </summary>
        [StringLength(200)]
        public string Address { get; set; }
        
        /// <summary>
        /// 最后登录时间
        /// </summary>
        public DateTime? LastLoginOn { get; set; }
        
        /// <summary>
        /// 最后登录IP
        /// </summary>
        [StringLength(20)]
        public string LastLoginIP { get; set; }
        
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime? CreateOn { get; set; }
        
        /// <summary>
        /// 创建人ID
        /// </summary>
        [StringLength(20)]
        public string CreateUserId { get; set; }
        
        /// <summary>
        /// 创建人名称
        /// </summary>
        [StringLength(50)]
        public string CreateBy { get; set; }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime? ModifiedOn { get; set; }
        
        /// <summary>
        /// 更新人Id
        /// </summary>
        [StringLength(20)]
        public string ModifiedUserId { get; set; }
        
        /// <summary>
        /// 更新人名称
        /// </summary>
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}
