//-----------------------------------------------------------------------
// <copyright file="BaseUserConfiguration.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BaseUserConfiguration.cs
// * history : Created by T4 11/27/2018 23:44:52 
// </copyright>
//-----------------------------------------------------------------------

using BuDing.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BuDing.Domain.Configurations
{
    using BuDing.Domain.Entities;

    /// <summary>
	/// BaseUserConfiguration Entity Repository
	/// </summary> 
	public class BaseUserConfiguration : IEntityTypeConfiguration<BaseUser>
	{
		public void Configure(EntityTypeBuilder<BaseUser> builder)
		{

			builder.HasKey(e => e.ID);

			builder.Property(e => e.ID).HasColumnName("ID")
					.HasMaxLength(20);

			builder.Property(e => e.Name).HasColumnName("Name")
					.HasMaxLength(50);

			builder.Property(e => e.Passwrod).HasColumnName("Passwrod")
					.HasMaxLength(255)	;

			builder.Property(e => e.DispName).HasColumnName("DispName")
					.HasMaxLength(255)
	;

			builder.Property(e => e.Sex).HasColumnName("Sex")
	;

			builder.Property(e => e.Mail).HasColumnName("Mail")
					.HasMaxLength(50)
	;

			builder.Property(e => e.Mobile).HasColumnName("Mobile")
					.HasMaxLength(20)
	;

			builder.Property(e => e.Avatar).HasColumnName("Avatar")
					.HasMaxLength(50)
	;

			builder.Property(e => e.IdentityCode).HasColumnName("IdentityCode")
					.HasMaxLength(30)
	;

			builder.Property(e => e.Address).HasColumnName("Address")
					.HasMaxLength(200)
	;

			builder.Property(e => e.LastLoginOn).HasColumnName("LastLoginOn")
	;

			builder.Property(e => e.LastLoginIP).HasColumnName("LastLoginIP")
					.HasMaxLength(20)
	;

			builder.Property(e => e.CreateOn).HasColumnName("CreateOn")
	;

			builder.Property(e => e.CreateUserId).HasColumnName("CreateUserId")
					.HasMaxLength(20)
	;

			builder.Property(e => e.CreateBy).HasColumnName("CreateBy")
					.HasMaxLength(50)
	;

			builder.Property(e => e.ModifiedOn).HasColumnName("ModifiedOn")
	;

			builder.Property(e => e.ModifiedUserId).HasColumnName("ModifiedUserId")
					.HasMaxLength(20)
	;

			builder.Property(e => e.ModifiedBy).HasColumnName("ModifiedBy")
					.HasMaxLength(50)
	;

		}
	}
}
