//-----------------------------------------------------------------------
// <copyright file="SysModuleConfiguration.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysModuleConfiguration.cs
// * history : Created by T4 11/27/2018 23:44:52 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BuDing.Domain.Configurations
{
    using BuDing.Domain.Entities;

    /// <summary>
    /// SysModuleConfiguration Entity Repository
    /// </summary> 
    public class SysModuleConfiguration:IEntityTypeConfiguration<SysModuleEntity>
    {
 		public void Configure(EntityTypeBuilder<SysModuleEntity> builder)
		{

				builder.HasKey(e => e.ID);	
 
        builder.Property(e => e.ID).HasColumnName("ID") 
;
		 
        builder.Property(e => e.ParentID).HasColumnName("ParentID") 
;
		 
        builder.Property(e => e.Code).HasColumnName("Code") 
				.HasMaxLength(100)
;
		 
        builder.Property(e => e.Name).HasColumnName("Name") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.DisplayName).HasColumnName("DisplayName") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.FullName).HasColumnName("FullName") 
				.HasMaxLength(50)
;
		 
        builder.Property(e => e.CategoryCode).HasColumnName("CategoryCode") 
				.HasMaxLength(50)
;
		 
        builder.Property(e => e.Url).HasColumnName("Url") 
				.HasMaxLength(500)
;
		 
        builder.Property(e => e.SortCode).HasColumnName("SortCode") 
;
		 
        builder.Property(e => e.IsMenu).HasColumnName("IsMenu") 
;
		 
        builder.Property(e => e.Icon).HasColumnName("Icon") 
				.HasMaxLength(100)
;
		 
        builder.Property(e => e.IsPublic).HasColumnName("IsPublic") 
;
		 
        builder.Property(e => e.IsEnabled).HasColumnName("IsEnabled") 
;
		 
        builder.Property(e => e.DeletionStateCode).HasColumnName("DeletionStateCode") 
;
		 
        builder.Property(e => e.IsVisable).HasColumnName("IsVisable") 
;
		 
        builder.Property(e => e.Remark).HasColumnName("Remark") 
				.HasMaxLength(300)
;
		 
        builder.Property(e => e.CreateOn).HasColumnName("CreateOn") 
;
		 
        builder.Property(e => e.CreateUserId).HasColumnName("CreateUserId") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.CreateBy).HasColumnName("CreateBy") 
				.HasMaxLength(50)
;
		 
        builder.Property(e => e.ModifiedOn).HasColumnName("ModifiedOn") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.ModifiedUserId).HasColumnName("ModifiedUserId") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.ModifiedBy).HasColumnName("ModifiedBy") 
				.HasMaxLength(50)
;

		}
    }
}
