//-----------------------------------------------------------------------
// <copyright file="SysRoleConfiguration.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysRoleConfiguration.cs
// * history : Created by T4 11/27/2018 23:44:52 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BuDing.Domain.Configurations
{
    using BuDing.Domain.Entities;

    /// <summary>
    /// SysRoleConfiguration Entity Repository
    /// </summary> 
    public class SysRoleConfiguration:IEntityTypeConfiguration<SysRoleEntity>
    {
 		public void Configure(EntityTypeBuilder<SysRoleEntity> builder)
		{

				builder.HasKey(e => e.ID);	
 
        builder.Property(e => e.ID).HasColumnName("ID") 
;
		 
        builder.Property(e => e.ModuleID).HasColumnName("ModuleID") 
;
		 
        builder.Property(e => e.Code).HasColumnName("Code") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.RealName).HasColumnName("RealName") 
				.HasMaxLength(50)
;
		 
        builder.Property(e => e.CateGoryCode).HasColumnName("CateGoryCode") 
				.HasMaxLength(50)
;
		 
        builder.Property(e => e.AllowEdit).HasColumnName("AllowEdit") 
;
		 
        builder.Property(e => e.AllowDelete).HasColumnName("AllowDelete") 
;
		 
        builder.Property(e => e.IsVisible).HasColumnName("IsVisible") 
;
		 
        builder.Property(e => e.SortCode).HasColumnName("SortCode") 
;
		 
        builder.Property(e => e.DeletionStateCode).HasColumnName("DeletionStateCode") 
;
		 
        builder.Property(e => e.IsEnabled).HasColumnName("IsEnabled") 
;
		 
        builder.Property(e => e.Description).HasColumnName("Description") 
				.HasMaxLength(100)
;
		 
        builder.Property(e => e.Remark).HasColumnName("Remark") 
				.HasMaxLength(300)
;
		 
        builder.Property(e => e.CreateOn).HasColumnName("CreateOn") 
;
		 
        builder.Property(e => e.CreateUserId).HasColumnName("CreateUserId") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.CreateBy).HasColumnName("CreateBy") 
				.HasMaxLength(50)
;
		 
        builder.Property(e => e.ModifiedOn).HasColumnName("ModifiedOn") 
;
		 
        builder.Property(e => e.ModifiedUserId).HasColumnName("ModifiedUserId") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.ModifiedBy).HasColumnName("ModifiedBy") 
				.HasMaxLength(50)
;

		}
    }
}
