//-----------------------------------------------------------------------
// <copyright file="SysUserRoleConfiguration.cs">
// * Copyright (C) 2018 Godric All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysUserRoleConfiguration.cs
// * history : Created by T4 11/27/2018 23:44:52 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BuDing.Domain.Configurations
{
    using BuDing.Domain.Entities;

    /// <summary>
    /// SysUserRoleConfiguration Entity Repository
    /// </summary> 
    public class SysUserRoleConfiguration:IEntityTypeConfiguration<SysUserRole>
    {
 		public void Configure(EntityTypeBuilder<SysUserRole> builder)
		{

				builder.HasKey(e => e.ID);	
 
        builder.Property(e => e.ID).HasColumnName("ID") 
;
		 
        builder.Property(e => e.RoleID).HasColumnName("RoleID") 
;
		 
        builder.Property(e => e.DeletionStateCode).HasColumnName("DeletionStateCode") 
;
		 
        builder.Property(e => e.IsEnabled).HasColumnName("IsEnabled") 
;
		 
        builder.Property(e => e.Description).HasColumnName("Description") 
				.HasMaxLength(100)
;
		 
        builder.Property(e => e.Remark).HasColumnName("Remark") 
				.HasMaxLength(300)
;
		 
        builder.Property(e => e.CreateOn).HasColumnName("CreateOn") 
;
		 
        builder.Property(e => e.CreateUserId).HasColumnName("CreateUserId") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.CreateBy).HasColumnName("CreateBy") 
				.HasMaxLength(50)
;
		 
        builder.Property(e => e.ModifiedOn).HasColumnName("ModifiedOn") 
;
		 
        builder.Property(e => e.ModifiedUserId).HasColumnName("ModifiedUserId") 
				.HasMaxLength(20)
;
		 
        builder.Property(e => e.ModifiedBy).HasColumnName("ModifiedBy") 
				.HasMaxLength(50)
;

		}
    }
}
